### ISSUE TITLE
This is just what I need

### ISSUE THREAD

**Issue by joaolucasd** [Nickduino/Somfy_Remote#16]
But I have zero knowledge when it comes to programming. I'm great at following tutorials, but that is it.
How can I hack the RF transmiter? How can I make this happen? Would you mind pointing me the right direction? 

Thank you!

**Comment by Nickduino** [comment]
Hi and sorry for the late answer.

Hack the RF transmitter: order a cheap Chinese one and replace the crystal oscillator.

How to make it happen: I don't have a detailed tutorial, nor will I ever make one, so you'll have to self-teach some skills yourself. The good news is that it will be easier than learning how to program like I did.
Start here:
https://github.com/Nickduino/Somfy_Remote/issues?utf8=%E2%9C%93&q=is%3Aissue

And possibly there:
https://github.com/Nickduino/Pi-Somfy/issues?utf8=✓&q=is%3Aissue
