### ISSUE TITLE
Sketch running on ESP8266

### ISSUE THREAD

**Issue by jktz90** [Nickduino/Somfy_Remote#18]
Hello,

did you try running your code on an ESP8266 basis? I tried it in combination with a CC1101 transmitter but it does not work. Does the digitalWrite routine mess up with the impuse timings?_

**Comment by Nickduino** [comment]
You'd have to replace the direct port manipulation with digitalWrite() and it should work.

Check out the forks, some people have successfully implemented it on the ESP8266.


I didn't feel the need myself because I've done a Python version running on my Raspberry Pi
