### ISSUE TITLE
Not working on Arduino mega

### ISSUE THREAD

**Issue by brainkiller** [Nickduino/Somfy_Remote#21]
I've recently bought a arduino mega and shield ready for rflink firmware (Arduino mega pinout: https://lynx2015.files.wordpress.com/2015/08/arduino-mega-pinout-diagram.png)
The connections are documented here: http://www.rflink.nl/blog2/images/rfl_sch.jpg
But I'm unable to figure how to adapt the port registry (I tried register J (DDRJ and PORTJ) but I'm not getting any response from the somfy engine.

Would you guys have some pointers to get this working ?

---------
#define PORT_TX 0 // 14 of PORTD = DigitalPin 14

void setup() {
  Serial.begin(115200);
  pinMode(15, OUTPUT);
  digitalWrite(15,HIGH);
  DDRJ |= 1 << PORT_TX; // Pin 5 an output
  PORTJ &= !(1 << PORT_TX); // Pin 5 LOW
---------

**Comment by Nickduino** [comment]
Easy pointer: forget the direct PORT manipulation and use digitalWrite instead, the timing isn't that critical 😉
