### ISSUE TITLE
Trying to get this to work on an ESP8266 - Compiling errors for PORTD and DDRD

### ISSUE THREAD

**Issue by Allthecoolnamesweretaken** [Nickduino/Somfy_Remote#22]
Hi and thanks for some interesting looking code. 

I've tried this on a Mega 2560 and it seems OK. When I tried to compile for an ESP8266, I got errors that PORTD and DDRD werent declared.

I gather PORTD and DDRD arent valid for the ESP8266.

I saw you did comment about using an ESP8266 yourself sometime - hàve you done that? How could the code be changed to achieve that?

Please bear in mind that I am a complete and utter newbie, so you'll probably need to explain like I am five.

Many thanks for any help you can offer.

**Comment by Nickduino** [comment]
Hey!

You could replace the direct PORT manipulation by the good old digitalWrite. Check the forks: some people did port my sketch to the ESP8266
