### ISSUE TITLE
Reliability Problem of RTS sending

### ISSUE THREAD

**Issue by Hollako** [Nickduino/Somfy_Remote#23]
Hello,

I am facing an issue of reliability with the 433.42 TX modules, I have 2 boards i replaced the 433.92 with the 433.42 MHz crystal.  Sometimes they work like charm and sometimes not. Am trying them on Arduino Uno since on ESP8266 is not working at all even if use the digitalWrite syntax.

Is the isuue may be related to the Antenna of the TX modules? and what is the preferable antenna to be added to the TX module for better coverage.

Noting that i modified the sketch to support up to 8 RTS remotes, i created many EEPROM addresses with 4 bytes reservation for each address and the RTS Remote addresses increment are 4 as well (i.e REMOTE1 address is 0x235440 the REMOTE2 is 0x235444)

Thank you.

**Comment by Nickduino** [comment]
Hum...I'm surprised you're encountering these problems. I personally found that the blinds are incredibly picky frequency-wise but not "antenna-wise"

I'm using an un-tuned coil for compactness but the better option would probably be a 17cm (a quarter of the wavelength, look it up on Google) wire with a ground plane.

When you modified the sketch, did you change the number of repetitions of the frame?



As for the ESP8266, have a look at the forks: some people ported my code.

**Comment by Hollako** [comment]
Hello,

What you mean by the repetitions of the frame? i just duplicated the commands x 8 and created a cases where i switch between REMOTE addresses and EEPROM addresses.

**Comment by Nickduino** [comment]
The sketch is sending the signal a few times. Maybe you should increase the number of repetitions, although it's not the most elegant solution
