### ISSUE TITLE
License

### ISSUE THREAD

**Issue by EinfachArne** [Nickduino/Somfy_Remote#24]
Hey Nickduino,

sorry to bother you this way but I found no other contact details. Could you add any kind of open source license to your project if you would like others like me to use it? Otherwise we are just not allowed to use your work and depend on your good will.

Thank you!

**Comment by Nickduino** [comment]
I'm happy for people to use my code non commercially as long as they attribute the code to me, do you have a licence to suggest?

**Comment by EinfachArne** [comment]
Maybe GPL or MIT fit your purpose. Just have a quick look at this site: https://choosealicense.com/

**Comment by Nickduino** [comment]
https://github.com/Nickduino/Somfy_Remote/commit/2c086d58ef8e90c85be6247993ea863c4e3c849d
