### ISSUE TITLE
‘class EEPROMClass’ has no member named ‘get’

### ISSUE THREAD

**Issue by Benjalien** [Nickduino/Somfy_Remote#25]
Hi,
I have a compilation issue: Somfy_Remote.ino:47:14: error: ‘class EEPROMClass’ has no member named ‘get’
I have this on an Arduino Uno, could it be that I do something wrong?
BR
Benjamin

**Comment by Benjalien** [comment]
I solved it, it was related to my IDE version :(
Sorry.

**Comment by Nickduino** [comment]
I'm glad you found a solution yourself because I haven't used the sketch in years...


Check out the Python version if you want to go further.
