### ISSUE TITLE
SYMBOL should be 604 and not 640

### ISSUE THREAD

**Issue by dov** [Nickduino/Somfy_Remote#27]
In the https://pushstack.wordpress.com/somfy-rts-protocol/ link you reference the SYMBOL length is 604us whereas in your sketch you use 640. I don't know if it's a type or the result of some experimentation.

**Comment by Nickduino** [comment]
Answered a few times already. There's a typo on Pushstack, it really is 640µs (check the patent). But it doesn't matter much, the blinds are pretty tolerant
