### ISSUE TITLE
support more then 1 blind

### ISSUE THREAD

**Issue by 4x4eb** [Nickduino/Somfy_Remote#28]
hi
I want to use one design to control several blinds.
how can I assign new commands like UP or DOWN for each blind individually(not group command)?

Thanks
Eitan

**Comment by Nickduino** [comment]
Either:

- Use Pi-Somfy: https://github.com/Nickduino/Pi-Somfy
- Or add this functionality to the Arduino script: https://github.com/Nickduino/Somfy_Remote/issues/4

**Comment by 4x4eb** [comment]
hi

thanks (-:

**Comment by 4x4eb** [comment]
another question please 

what is the reason for these lines?

if (EEPROM.get(EEPROM_ADDRESS, rollingCode) < newRollingCode) {
    EEPROM.put(EEPROM_ADDRESS, newRollingCode);

**Comment by Nickduino** [comment]
The code sent by your remote change every time you use it (so that someone can't record it and play it back later), that's a rolling code. I store the current code in the EEPROM, so that you can power the Arduino off and not loose the sync.

**Comment by 4x4eb** [comment]
hi and thanks for the fast answer.

writing the last code to eeprom- I understand .
why do u compare it every power on to NEWROLLINGCODE ? its kind of constant as I understand.

Thanks for helping

**Comment by Nickduino** [comment]
> writing the last code to eeprom- I understand . why do u compare it every power on to NEWROLLINGCODE ? its kind of constant as I understand.
> 


IIRC I wanted to be able to change the rolling code when uploading the sketch (if the const rolling code you set in the sketch is higher than the one in EEPROM, it will overwrite the latter with the former)
