### ISSUE TITLE
Library Version

### ISSUE THREAD

**Issue by Legion2** [Nickduino/Somfy_Remote#29]
I created an Arduino Library based on this project https://github.com/Legion2/Somfy_Remote_Lib. It supports Arduino, ESP32 and  ESP8266. It can be downloaded in the Arduino IDE via the Library Manager.

**Comment by Nickduino** [comment]
A library is a very good idea, thanks for having done this work.

In some circumstances, you may want it to run on a Raspberry Pi. Have you checked the Python version? https://github.com/Nickduino/Pi-Somfy

**Comment by Legion2** [comment]
No, I'm using it with https://github.com/1technophile/OpenMQTTGateway and OpenHAB, so it is well integrated in my smart home setup.

**Comment by Nickduino** [comment]
Perfect

**Comment by Legion2** [comment]
I also want to add that the CC1101 transceiver module is a very good alternative to self made 433.42 MHz modules. It is a drop in replacement for sending and receiving, the only drawback is that it requires a SPI connection to configure the frequency.

**Comment by Nickduino** [comment]
Alright, I now  mention it in the README.md
