### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by afoeder** [Nickduino/Somfy_Remote#31]
Hi @Nickduino, thanks a lot for your inspiring work that apparently is the baseline for many others :)

Would you please provide a license to your source code so that we can properly attribute you following the terms you've wished?

Thanks a lot!

**Comment by Nickduino** [comment]
Glad you like it. Have you checked the (much more developed) Python version?

As for the licence, wouldn't that be enough?
![Screenshot_2021-03-21-19-28-45-656_com android chrome~2](https://user-images.githubusercontent.com/9784237/111916549-cbd0c780-8a7b-11eb-8320-d3777bf31dfa.jpg)

**Comment by afoeder** [comment]
ah, I apptly overlooked it looking for a LICENSE.md file or traces in the source code; thanks a lot!

I did check the python one but I specifically wanted to use an ESP so I went with this one.

Thanks again!

//edit: I'll provide a PR though you can decide then whether to accept it. cheers!
