### ISSUE TITLE
Simulate Long-Press

### ISSUE THREAD

**Issue by tfcarlin** [Nickduino/Somfy_Remote#34]
I have a working version of the software but have misplaced the physical remote. Thus I can no longer:

"Long-press the program button of YOUR ACTUAL REMOTE until your blind goes up and down slightly"

to put the blind in Program mode (I would like to create a back up of the current remote using a new channel). Is there a way to simulate a "Long-press" using your code?

Thanks for the assistance.

**Comment by Nickduino** [comment]
Read your blind's documentation: there is a way (like powering it off, on, off and on again for a set period).

Or send a longer press with the python code
