### ISSUE TITLE
max number of remotes per shade?

### ISSUE THREAD

**Issue by rthiel** [Nickduino/Somfy_Remote#35]
Hi together,
I played around with the sketch and it's working now for me. I control multiple shades (each with an own remote address). The problem I have that one shade doesn't work (the one I used for the first experiments). When I program it, shades go up and down but then the normal modes (up / down / my) don't work. --> sounds a bit like the wrong rollingcode although I send an initial one at the prog stage and count up then (same as for all the other shades where it works).
How many remotes are possible for one shade? I tried a lot and for that specific shade I definitly used >10 random addresses already. Is it possible that the shade just strores a few ones and doesn't accept to learn a new one (although the reaction at the programming step is the same as for the ones working (up/down swipe)). 
Any idea how to find out what addresses are stored internally and how to delete them?
thanks in advance

**Comment by Nickduino** [comment]
Check the documentation for the blind, there should be a procedure to empty the memory
