### ISSUE TITLE
Symbol lengh 604 or 640?

### ISSUE THREAD

**Issue by Zitrium31** [Nickduino/Somfy_Remote#38]
Hi Nick,

First of all : Thanks much for sharing your great work !

Reviewing your codes, I have noticed that the frame symbol lenght is set to 640 µS whereas the "Pushstack web page" defines the Somfy RTS protocol with a 604µS. Is this a typo or could you advise why you adjust the value not in line with Pushstack RTS documentation?

Thank you in advance !

Link to Somfy_Remote.ino / Line L24:
https://github.com/Nickduino/Somfy_Remote/blob/3f58d5365a9d964a87019c6f7f8aee6f5f5a867d/Somfy_Remote.ino#L24

Pushstack web page:
https://pushstack.wordpress.com/somfy-rts-protocol/

**Comment by Nickduino** [comment]
Asked and answered many times here. It's 640, there's a typo on Pushstack.

It doesn't really matter, though, it seems to work with 604 too.
