### ISSUE TITLE
Hardware not working

### ISSUE THREAD

**Issue by eliemada** [Nickduino/Somfy_Remote#39]
Hi 
Thanks again for this code, 
I am currently facing an issue, i bought everything necessary, setted up my esp, and did the crystal swap.
I enter into prog mode, push p using mqtt, but the blinds are not reacting, i tried with the default and swapped crystal. Nothing changes, 
How can i do ? 
What am i suppose to do ?
I copied the wiring from
https://www.youtube.com/watch?v=9RhHrYqp9FU
Nothing works 
Please help me

**Comment by Nickduino** [comment]
Not the right repository
