### ISSUE TITLE
Using with multiple blinds

### ISSUE THREAD

**Issue by nick1802** [Nickduino/Somfy_Remote#4]
Hey nickduino,

Is it possible to control up to 11 blinds separately?  If so how would I go about it?

Thanks in advance,
Nick

**Comment by Nickduino** [comment]
Absolutely!

You just have to create 11 remote addresses (line 31), reserve 11 EEPROM adresses (line 29) and make sure you refer to the right remote in the code when you want to control the blinds.

**Comment by nick1802** [comment]
Thanks Nickduino!
