### ISSUE TITLE
DDRD and PORTD not declared before first use.

### ISSUE THREAD

**Issue by gnaeser** [Nickduino/Somfy_Remote#6]
They just need to be declared ; )

**Comment by Nickduino** [comment]
They are direct port manipulations and shouldn't have to be declared:
https://www.arduino.cc/en/Reference/PortManipulation


If you're not comfortable with that, check this out:
https://github.com/caffineehacker/Somfy_Remote/commit/aa2b4a65f3a2240f1e37c00c56543d63ef30bf3a

**Comment by gnaeser** [comment]
Hi,

Thanks for the pointers! I'll just refactor then to allow other architectures, like the esp8266!

Keep up the great work!


/gaffe

**Comment by Nickduino** [comment]
You're welcome.

And thanks for your appreciation.
